### ISSUE TITLE
Improve compile-time error messages from log-derive

### ISSUE THREAD

**Issue by TedDriggs** [elichai/log-derive#5]
Misspelling a meta-item name (or other errors) cause error messages that highlight the entire attribute and don't clearly spell out what's wrong.

![compile error](https://user-images.githubusercontent.com/4805575/52384800-d367ba80-2a33-11e9-9853-2b1c01327a41.png)

My fix for this in the past has been twofold:

1. Have a `Result` type for parsing options, and a `Vec` for collecting all errors encountered during parsing. The error type should be remembering the span where the error was encountered.
2. Before building the `Attributes` struct, check if the list of errors is empty. If so, emit each error. `syn::Error` works well for this.

Note that I found this tedious enough that I created a library to help with the bookkeeping, called `darling`. The `darling::Error` type has the functionality you'd need for this, though you could also directly wrap `syn`'s error if you want to keep the dependency list small.

**Comment by elichai** [comment]
Ha. You're saying I should use `syn::Error` instead of panicking?
I was just talking with @dtolnay about compile errors in proc-macros (actually about code errors not erros in the macro, and he pointed me to this: https://github.com/rust-lang/rust/issues/43081 )

I'll look into this.

Thanks for the thorough review and issues :)
